services:
  backend:
    build:
      context: ./vibecheck-backend
      dockerfile: VibeCheck.PL/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__VibeCheckContext=Host=postgres;Database=VibeCheck;Username=postgres;Password=150903
    depends_on:
      - postgres


  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 150903
      POSTGRES_DB: VibeCheck
    ports:
      - "5432:5432"  # Exposing port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: