# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy VibeCheck to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./vibecheck-backend/VibeCheckSolution.sln
        
      - name: Build with dotnet
        run: dotnet build ./vibecheck-backend/VibeCheckSolution.sln --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish ./vibecheck-backend/VibeCheck.PL/VibeCheck.PL.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4CD6FA735D894EAEACBA3098AF09E3B4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BB2ED5B3C0FE4C69AC5191B4DEDEDB30 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ADB92C23B01740C8828D07BA639F3177 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'VibeCheck'
          slot-name: 'Production'
          package: .
          
      - name: Configure App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'VibeCheck'
          app-settings-json: |
            [
              {
                "name": "ASPNETCORE_ENVIRONMENT",
                "value": "Production"
              },
              {
                "name": "WEBSITES_ENABLE_APP_SERVICE_STORAGE",
                "value": "true"
              },
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "false"
              }
            ]
          connection-strings-json: |
            [
              {
                "name": "VibeCheckContext",
                "value": "${{ secrets.CONNECTION_STRING }}",
                "type": "PostgreSQL"
              }
            ]
